name: exifly.it

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: exifly.it

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up -d 
